CREATE TABLE BOARD(
	BID INT PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	CONTENT VARCHAR(100) NOT NULL,
	CNT INT DEFAULT 0,
	REGDATE DATE DEFAULT SYSDATE
);

INSERT INTO BOARD(BID,TITLE,WRITER,CONTENT) VALUES(2,'力格','包府磊','郴侩');

SELECT * FROM BOARD WHERE TITLE LIKE ' ' AND WRITER LIKE '' ORDER BY BID DESC;

SELECT * FROM BOARD;
DROP TABLE BOARD;

SELECT * FROM BOARD WHERE ' ' LIKE '%力%' ORDER BY BID DESC;